### ISSUE TITLE
Write down all tasks of each python script

### ISSUE THREAD

**Issue by mwakok** [SATAY-LL/LaanLab-SATAY-DataAnalysis#51]
**Observation**
- Code base is partially modular, but existing scripts contain many functionalities/tasks
- Scripts with many tasks are difficult to maintain
- Scripts with many tasks are difficult to test as only separate functions can be tested. When a script contains multiple functionalities that are not written as functions, they can only be tested as part of the whole script, not separately.
- Following best practices, a function should be small and do only one thing

**Proposed solution**
- [x] Write down a list of tasks in each script to create an overview of all functionalities
- [x] Design a project structure that organises these tasks

**Comment by leilaicruz** [comment]
how do think will be the best way to write those tasks? in a separate file , in which format? for example like a .txt file with the same name as the script with the tasks listed ?

what about the tests of the overall functionality of each script?  
I think the approach for testing for the python scripts should be different than for the bash scripts for the sequencing analysis part.
